homepage: "https://github.com/klauspost/compress"
primary_contact: "klauspost@gmail.com"
auto_ccs:
  - "p.antoine@catenacyber.fr"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: 'https://github.com/klauspost/compress'
