homepage: "https://docs.rs/image/0.23.14/image/"
main_repo: "https://github.com/image-rs/image-png"
primary_contact: "david@adalogics.com"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
language: rust
auto_ccs:
  - "david@adalogics.com"
