homepage: "https://github.com/uriparser/uriparser"
language: c++
primary_contact: "webmaster@hartwork.org"
sanitizers:
 - address
 - memory:
    experimental: True
 - undefined
architectures:
  - x86_64
  - i386
