homepage: "https://github.com/libvips/libvips"
primary_contact: "jcupitt@gmail.com"
auto_ccs:
  - "oscar.mira@adevinta.com"
  - "kleisauke@gmail.com"
  - "lovell.fuller@gmail.com"
architectures:
  - x86_64
  - i386
