homepage: "https://knative.dev/"
language: go
primary_contact: ""
main_repo: "https://github.com/knative"
vendor_ccs:
  - "adam@adalogics.com"
  - "david@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
