homepage: "https://pybind11.readthedocs.io/en/stable/"
main_repo: "https://github.com/pybind/pybind11.git"
language: c++
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
vendor_ccs:
 - "david@adalogics.com"
 - "arthur.chan@adalogics.com"
