homepage: "https://pkg.go.dev/github.com/google/go-cmp/"
primary_contact: "joetsai@digital-static.net"
auto_ccs:
  - "p.antoine@catenacyber.fr"
language: go
fuzzing_engines:
- libfuzzer
sanitizers:
- address
main_repo: 'https://github.com/google/go-cmp/'
