homepage: "https://github.com/square/javapoet"
language: jvm
primary_contact: "irali@google.com"
main_repo: "https://path/to/main/repo.git"
auto_ccs:
  - "himkhurana@google.com"
  - "atulag@google.com"
  - "rashmivirdy@google.com"
sanitizers:
  - address
