homepage: "https://github.com/encode/httpx"
language: python
main_repo: "https://github.com/encode/httpx"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
vendor_ccs:
  - maxnair.dev@gmail.com
