homepage: "https://github.com/isaacs/node-tar"
language: javascript
primary_contact: "dnnkskn@gmail.com"
main_repo: "https://github.com/isaacs/node-tar.git"
fuzzing_engines:
- libfuzzer
sanitizers:
- none