homepage: "https://github.com/handlebars-lang/handlebars.js"
language: javascript
primary_contact: ""
main_repo: "https://github.com/handlebars-lang/handlebars.js"
vendor_ccs:
  - maxnair.dev@gmail.com
fuzzing_engines:
  - libfuzzer
sanitizers:
  - none
