homepage: "https://docs.rs/scrypt"
main_repo: "https://github.com/RustCrypto/password-hashes"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
language: rust
auto_ccs:
  - "arthur.chan@adalogics.com"
  - "david@adalogics.com"
