auto_ccs:
- hj.tedd.an@gmail.com
- david@adalogics.com
- for.the.dawn.chorus@gmail.com
homepage: https://github.com/bluez/bluez
language: c
main_repo: https://github.com/bluez/bluez
primary_contact: bluez.test.bot@gmail.com
