homepage: "https://developers.google.com/protocol-buffers"
language: c++
primary_contact: "p.antoine@catenacyber.fr"
auto_ccs:
- protobuf-oss-fuzz@google.com

architectures:
- x86_64
- i386

sanitizers:
  - address
  - memory
  - undefined

fuzzing_engines:
  - libfuzzer
  - afl

main_repo: https://github.com/protocolbuffers/protobuf
