homepage: "https://pypi.org/project/invoice2data/0.2.13/"
language: python
primary_contact: "c5e2fd43-d292-4c90-9d1f-74ff3436329a@anonaddy.me"
auto_ccs: 
  - "ennamarie19@gmail.com"
fuzzing_engines: 
  - libfuzzer
sanitizers: 
  - address
  - undefined
main_repo: "https://github.com/invoice-x/invoice2data.git"
