auto_ccs:
- gray@gnu.org
- for.the.dawn.chorus@gmail.com
homepage: https://www.gnu.org.ua/software/gdbm
language: c
main_repo: https://git.gnu.org.ua/gdbm.git
primary_contact: sergey.poznyakoff@gmail.com
