auto_ccs:
- adam@adalogics.com
- for.the.dawn.chorus@gmail.com
homepage: https://github.com/vstakhov/libucl
language: c
main_repo: https://github.com/vstakhov/libucl
primary_contact: vsevolod@highsecure.ru
