homepage: "'https://github.com/catenacyber/ngolo-fuzzing"
primary_contact: "p.antoine@catenacyber.fr"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
architectures:
  - x86_64
  - i386
  - aarch64
main_repo: 'https://github.com/catenacyber/ngolo-fuzzing'
file_github_issue: True
