homepage: "https://www.freedesktop.org/wiki/Software/dbus"
language: c
primary_contact: ""
builds_per_day: 4
sanitizers:
  - address
  - undefined
  - memory
auto_ccs:
  - evverx@gmail.com
main_repo: "https://gitlab.freedesktop.org/dbus/dbus.git"
architectures:
  - x86_64
  - i386
