homepage: "https://github.com/libp2p/go-libp2p"
primary_contact: ""
vendor_ccs :
  - "bhargava.shastry@ethereum.org"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: 'https://github.com/libp2p/go-libp2p'
