homepage: "https://github.com/google/skia"
primary_contact: "kjlubick@chromium.org"
auto_ccs:
  - "hcm@chromium.org"
  - "mtklein@chromium.org"
sanitizers:
 - address
 - undefined:
    experimental: True
 - memory
