homepage: "http://freeimage.sourceforge.net/"
language: c++
primary_contact: "drolon@infonie.fr"

sanitizers:
  - address
  - undefined

labels:
  load_from_memory_fuzzer:
    - sundew

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

