homepage: "https://github.com/yhirose/cpp-httplib"
language: c++
primary_contact: "yuji.hirose.bug@gmail.com"
auto_ccs :
  - "omkarjadhav@google.com"
sanitizers:
  - address
  - dataflow
  - undefined
architectures:
  - x86_64