auto_ccs:
- Adam@adalogics.com
- tomasz.zawadzki@intel.com
- konrad.sztyber@intel.com
- michal.berger@intel.com
- for.the.dawn.chorus@gmail.com
homepage: https://github.com/spdk/spdk
language: c
main_repo: https://github.com/spdk/spdk
primary_contact: james.r.harris@intel.com
sanitizers:
- address
- undefined
- memory
