homepage: "https://github.com/python-pillow/Pillow"
language: python
primary_contact: "david@adalogics.com"
auto_ccs:
  - "security@python-pillow.org"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
