homepage: "https://github.com/spiraldb/vortex"
primary_contact: "robert@spiraldb.com"
main_repo: "https://github.com/spiraldb/vortex"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
language: rust
file_github_issue: True
