homepage: 'https://pybamm.org'
language: python
primary_contact: "pybamm@pybamm.org"
auto_ccs:
sanitizers:
  - address
  - memory:
     experimental: True
  - undefined
main_repo: 'https://github.com/pybamm-team/PyBaMM'