fuzzing_engines:
- libfuzzer
homepage: https://github.com/intel/ai-containers
language: python
main_repo: https://github.com/intel/ai-containers
sanitizers:
- address
vendor_ccs:
- tyler.titsworth@intel.com
- jitendra.patil@intel.com
- clayne.b.robison@intel.com
- srikanth.ramakrishna@intel.com
- sharvil.shah@intel.com
