homepage: "https://www.tensorflow.org"
language: c++
primary_contact: "lpak@google.com"
auto_ccs:
 - "itaiz@google.com"
 - "mihaimaruseac@google.com"
sanitizers:
  - address
  - undefined
  - memory
main_repo: 'https://github.com/tensorflow/tensorflow'
