auto_ccs:
- mom040267@gmail.com
- gustavogb@gmail.com
- ajsinghyadav00@gmail.com
- for.the.dawn.chorus@gmail.com
fuzzing_engines:
- libfuzzer
- afl
- honggfuzz
homepage: https://github.com/coturn/coturn
language: c
main_repo: https://github.com/coturn/coturn
primary_contact: misi@majd.eu
sanitizers:
- address
- memory
- undefined
