homepage: "https://nghttp2.org/"
language: c++
primary_contact: "tatsuhiro.t@gmail.com"
auto_ccs:
  - "david@adalogics.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - centipede
sanitizers:
  - address
  - undefined
  - memory
main_repo: 'https://github.com/nghttp2/nghttp2.git'
