homepage: "https://www.exiv2.org"
language: c++
primary_contact: "kevinbackhouse@github.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
main_repo: 'https://github.com/Exiv2/exiv2'
