homepage: "https://proton.me"
language: go
primary_contact: "security@proton.me"
auto_ccs:
  - "pkillarjun@protonmail.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: "https://github.com/ProtonMail/proton-bridge.git"
