auto_ccs:
- for.the.dawn.chorus@gmail.com
homepage: https://github.com/kkos/oniguruma
language: c
main_repo: https://github.com/kkos/oniguruma.git
primary_contact: kkosako0@gmail.com
sanitizers:
- address
- undefined
- memory
