homepage: "https://github.com/libbpf/libbpf"
language: c
primary_contact: ""
sanitizers:
  - address
  - undefined
  - memory
auto_ccs:
  - evverx@gmail.com
main_repo: 'https://github.com/libbpf/libbpf'
