homepage: "https://fastapi.tiangolo.com/"
main_repo: "https://github.com/tiangolo/fastapi"
language: python
primary_contact: "tiangolo@gmail.com"
auto_ccs:
  - "byone.heng@google.com"

fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined