homepage: "https://github.com/apple/swift-nio"
language: swift
primary_contact: "tkientzle@apple.com"
auto_ccs :
- "cory@lukasa.co.uk"
- "p.antoine@catenacyber.fr"

fuzzing_engines:
- libfuzzer
sanitizers:
- address
main_repo: 'https://github.com/apple/swift-nio.git'
