homepage: "https://github.com/platformdirs/platformdirs"
language: python
main_repo: "https://github.com/platformdirs/platformdirs"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
vendor_ccs:
  - david@adalogics.com
