homepage: "https://github.com/OWASP/Amass"
language: go
primary_contact: "sherif.mansour@owasp.org"
auto_ccs:
  - "jeff.foley@owasp.org"
sanitizers:
  - address
  - memory:
     experimental: True
  - undefined
