homepage: "https://www.webmproject.org"
primary_contact: "jzern@google.com"
sanitizers:
- address
- memory
- undefined
auto_ccs:
- jzern@google.com
- johannkoenig@google.com
architectures:
  - x86_64
  - i386
