homepage: "https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS"
primary_contact: "fkiefer@mozilla.com"
auto_ccs:
  - "jjones@mozilla.com"
  - "sledru@mozilla.com"
  - "kjacobs@mozilla.com"
fuzzing_engines:
  - libfuzzer
  - afl
