homepage: "http://www.pcre.org/"
language: c++
primary_contact: "philip.hazel@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - centipede
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
