auto_ccs:
- cryptomilk@gmail.com
- jakuje@gmail.com
- anderson.sasaki@gmail.com
- for.the.dawn.chorus@gmail.com
homepage: https://libssh.org/
language: c
main_repo: https://git.libssh.org/projects/libssh.git
primary_contact: asn@cryptomilk.org
sanitizers:
- address
- undefined
