homepage: "https://lxml.de/"
language: python
primary_contact: "david@adalogics.com"
auto_ccs:
  - "david@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
main_repo: 'https://github.com/lxml/lxml/'
