homepage: "https://javaparser.org"
language: jvm
primary_contact: "TODO"
auto_ccs:
  - "p.antoine@catenacyber.fr"
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/javaparser/javaparser"
sanitizers:
  - address
