homepage: "https://www.qubes-os.org/"
language: c++
primary_contact: "jpo@vt.edu"
auto_ccs:
  - "marmarek@invisiblethingslab.com"
  - "pawel@invisiblethingslab.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - centipede
sanitizers:
  - address
  - undefined
architectures:
  - x86_64
  - i386
