homepage: "https://www.behaviortree.dev/"
language: c++
primary_contact: "christopher.krah@unikie.com"
main_repo: "https://github.com/BehaviorTree/BehaviorTree.CPP"
file_github_issue: true
vendor_ccs:
  - "dfaconti@aurynrobotics.com"
