homepage: "https://github.com/mongodb/mongo-go-driver"
language: go
main_repo: "https://github.com/mongodb/mongo-go-driver"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
vendor_ccs:
  - maxnair.dev@gmail.com
