homepage: "https://about.validator.nu/htmlparser/"
language: jvm
primary_contact: "someone@validator-html.com"
main_repo: "https://github.com/validator/htmlparser"
auto_ccs:
  - "david@adalogics.com"
