homepage: "https://github.com/blang/semver"
primary_contact: "github@benediktlang.de"
auto_ccs:
  - "p.antoine@catenacyber.fr"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: 'https://github.com/blang/semver'
