fuzzing_engines:
- libfuzzer
homepage: https://github.com/AzureAD/microsoft-authentication-library-for-python
language: python
main_repo: https://github.com/AzureAD/microsoft-authentication-library-for-python
sanitizers:
- address
vendor_ccs:
- david@adalogics.com
- adam@adalogics.com
- arthur.chan@adalogics.com
