homepage: "https://github.com/hsivonen/encoding_rs"
language: rust
main_repo: "https://github.com/hsivonen/encoding_rs"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
vendor_ccs:
  - maxnair.dev@gmail.com
