homepage: "https://github.com/hsivonen/encoding_rs"
language: rust
main_repo: "https://github.com/hsivonen/encoding_rs"
primary_contact: "hsivonen@gmail.com"
auto_ccs:
  - hsivonen@mozilla.com
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
vendor_ccs:
  - maxnair.dev@gmail.com
