homepage: "https://github.com/sunng87/handlebars-rust"
language: rust
main_repo: "https://github.com/sunng87/handlebars-rust"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
vendor_ccs:
  - maxnair.dev@gmail.com
