homepage: "https://racket-lang.org"
primary_contact: "pocmatos@gmail.com"
auto_ccs:
  - samth@racket-lang.org
sanitizers:
 - undefined
 - memory:
    experimental: True
 - address:
    experimental: True
architectures:
 - x86_64
 - i386
