homepage: "https://github.com/JoshData/python-email-validator"
language: python
primary_contact: ""
auto_ccs:
  - "maxnair.dev@gmail.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
main_repo: "https://github.com/JoshData/python-email-validator"
file_github_issue: true
