homepage: "https://www.xpdfreader.com/"
main_repo: 'https://gitlab.freedesktop.org/freetype/freetype'
primary_contact: "xpdf@xpdfreader.com"
language: c++
sanitizers:
  - address
auto_ccs :
  - "david@adalogics.com"
