homepage: "https://github.com/civetweb/civetweb"
primary_contact: "david@adalogics.com"
language: c
fuzzing_engines:
  - libfuzzer
  - honggfuzz
  - dataflow
auto_ccs:
  - "david@adalogics.com"
main_repo: 'https://github.com/civetweb/civetweb'
