auto_ccs:
- david@adalogics.com
- for.the.dawn.chorus@gmail.com
homepage: http://www.postfix.org/
language: c
main_repo: https://github.com/vdukhovni/postfix
primary_contact: wietse@gmail.com
sanitizers:
- address
