homepage: "https://github.com/google/zopfli"
primary_contact: "<primary_contact_email>"
auto_ccs:
  - "security-tps@google.com"
fuzzing_engines:
  - libfuzzer
  - afl
sanitizers:
  - address
  - memory
  -undefined
