homepage: "https://github.com/dask/dask"
main_repo: "https://github.com/dask/dask"
language: python
primary_contact: "david@adalogics.com"
auto_ccs :
  - "adam@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
