homepage: "https://github.com/google/snappy"
primary_contact: "storage-dev@chromium.org"
auto_ccs:
  - "bshas3@gmail.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
