homepage: "http://github.com/gogo/protobuf/"
primary_contact: "awalterschulze@gmail.com"
auto_ccs:
  - "p.antoine@catenacyber.fr"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: 'https://github.com/gogo/protobuf/'
