# Provide the home page for *your* project:
homepage: "https://github.com/rdkit/rdkit"

# Language the project is written in:
language: c++

# Provide the e-mail for the primary contact and others:
# Un-comment the below lines to make auto-cc work.
primary_contact: "greg.landrum@gmail.com"
# auto_ccs:  
#   - "secondary-my-api-maintainer@example.com"
#   - "tertiary-my-api-maintainer@example.com"
