homepage: "https://github.com/radareorg/radare2"
language: c++
primary_contact: "pancake@nopcode.org"
auto_ccs:
  - "zlowram@gmail.com"
sanitizers:
  - address
run_tests: false
main_repo: 'https://github.com/radareorg/radare2'
fuzzing_engines:
  - libfuzzer
  - centipede
