fuzzing_engines:
- libfuzzer
homepage: https://github.com/cowtowncoder/java-uuid-generator
language: jvm
main_repo: https://github.com/cowtowncoder/java-uuid-generator
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
- adam@adalogics.com
- arthur.chan@adalogics.com
