homepage: "https://github.com/google/brotli"
primary_contact: "eustas@chromium.org"
auto_ccs:
  - cdiehl@mozilla.com
fuzzing_engines:
  - libfuzzer
  - afl
  - dataflow
sanitizers:
  - address
  - dataflow
  - memory
  - undefined
