auto_ccs:
- david@adalogics.com
- for.the.dawn.chorus@gmail.com
homepage: https://www.prevanders.net/dwarf.html
language: c
main_repo: https://github.com/davea42/libdwarf-code
primary_contact: davea42@gmail.com
