homepage: "https://github.com/supranational/blst"
language: c++
primary_contact: "guidovranken@gmail.com"
main_repo: "https://github.com/supranational/blst.git"
sanitizers:
 - address
 - undefined
architectures:
 - x86_64
 - i386
