homepage: "https://github.com/syoyo/tinygltf"
language: c++
primary_contact: "p.antoine@catenacyber.fr"
fuzzing_engines:
  - libfuzzer
  - centipede
sanitizers:
  - address
main_repo: 'https://github.com/syoyo/tinygltf.git'
