# action.yml
name: 'build-fuzzers'
description: 'Builds an OSS-Fuzz projects fuzzers.'
inputs:
  oss-fuzz-project-name:
    description: 'Name of the corresponding OSS-Fuzz project.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    OSS_FUZZ_PROJECT_NAME: ${{ inputs.oss-fuzz-project-name }}
