homepage: "https://www.libreoffice.org/"
language: c++
primary_contact: "caolanm@redhat.com"
sanitizers:
  - address
  - memory:
      experimental: true
  - undefined
fuzzing_engines:
  # see https://github.com/google/oss-fuzz/issues/6233 for missing afl
  - libfuzzer
  - honggfuzz
  - centipede
builds_per_day: 2
auto_ccs:
  - "damjan.jov@gmail.com"
  - "noelgrandin@gmail.com"
  - "sbergman@redhat.com"
main_repo: 'https://git.libreoffice.org/core'
