homepage: "https://opensource.google/projects/cel"
language: c++
primary_contact: "kyessenov@gmail.com"
auto_ccs :
- "p.antoine@catenacyber.fr"

sanitizers:
- address
main_repo: 'https://github.com/google/cel-cpp'
