homepage: "https://github.com/pelletier/go-toml"
language: go
main_repo: "https://github.com/pelletier/go-toml"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
vendor_ccs:
  - maxnair.dev@gmail.com
