auto_ccs:
- for.the.dawn.chorus@gmail.com
fuzzing_engines:
- libfuzzer
homepage: https://libwebsockets.org
language: c
main_repo: https://libwebsockets.org/repo/libwebsockets
primary_contact: andy.warmcat.com@googlemail.com
sanitizers:
- address
