homepage: "https://libwebsockets.org"
language: c
primary_contact: "andy.warmcat.com@googlemail.com"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
  - centipede
main_repo: 'https://libwebsockets.org/repo/libwebsockets'
