auto_ccs:
- dbn@endlessos.org
- david@adalogics.com
- for.the.dawn.chorus@gmail.com
homepage: https://github.com/ostreedev/ostree
language: c
main_repo: https://github.com/ostreedev/ostree
primary_contact: walters@verbum.org
