homepage: "https://github.com/google/shaderc"
main_repo: "https://github.com/google/shaderc.git"
primary_context: "david@adalogics.com"
language: c++
auto_ccs:
- "arthur.chan@adalogics.com"
- "adam@adalogics.com"
