homepage: "https://www.tensorflow.org"
language: python
primary_contact: "amitpatankar@google.com"
auto_ccs:
 - "mihaimaruseac@google.com"
sanitizers:
  - address
  - undefined
  - memory
main_repo: 'https://github.com/tensorflow/tensorflow'
