homepage: "nokogiri.org"
language: c
primary_contact: "nokogiri-oss-fuzz@googlegroups.com"
main_repo: 'https://github.com/sparklemotion/nokogiri.git'
sanitizers:
  - address
  - undefined
architectures:
  - x86_64
fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer