homepage: "https://github.com/bytedance/sonic"
primary_contact: "dysghappy@163.com"
auto_ccs:
  - "byone.heng@google.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
view_restrictions: none