homepage: "https://open62541.org/"
primary_contact: "Stefan.Profanter@gmail.com"
auto_ccs:
 - "julius.pfrommer@gmail.com"
 - "chris_paul.iatrou@tu-dresden.de"
sanitizers:
- address
- undefined
- memory
architectures:
  - x86_64
  - i386
