homepage: "https://github.com/assimp/assimp"
primary_contact: "kim.kulling@googlemail.com"
auto_ccs:
  - "kim.kulling@googlemail.com"
sanitizers:
  - address
  - memory:
     experimental: True
  - undefined