name: "pslab-python"
description: "PSLab is an open-source hardware and software platform for building science experiments and learning tools."
language: "python"
homepage: "https://pslab.io/"
main_repo: "https://github.com/fossasia/pslab-python.git"
issue_tracker: "https://github.com/fossasia/pslab-python/issues"
primary_contact: "alexander.bessman@gmail.com"
fuzzing_engines:
  - "libfuzzer"
sanitizers:
  - "address"
  - "undefined"
  - "memory"
  - "thread"
