homepage: "https://github.com/AsheChang/WebGoat"
language: JavaScript
primary_contact: "ashe_chang@gss.com.tw"
auto_ccs:
  - "vanessaghoul07@gmail.com"
main_repo: 'https://github.com/AsheChang/WebGoat.git'
