homepage: "abseil.io"
language: c++
primary_contact: "abseil-io@googlegroups.com"
main_repo: 'https://github.com/abseil/abseil-cpp.git'
sanitizers:
  - address
  - undefined
architectures:
  - x86_64
fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer