homepage: 'https://nixos.org/'
language: c++
primary_contact: 'edolstra@gmail.com'
# TODO: auto_ccs:
# See https://nixos.org/community/teams/security.html .
sanitizers:
- address
- coverage
- undefined
main_repo: 'https://github.com/nixos/nix'
