[package]
name = "http-fuzz"
version = "0.0.0"
authors = ["David Korczynski <david@adalogics.com>"]
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.3"
http = "0.2"

[[bin]]
name = "fuzz_http"
path = "src/fuzz_http.rs"

[workspace]

