homepage: "https://github.com/bufbuild/protocompile"
primary_contact: "jhumphries@buf.build"
auto_ccs:
  - "p.antoine@catenacyber.fr"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: 'https://github.com/bufbuild/protocompile'
