homepage: "https://github.com/ethereum/go-ethereum"
primary_contact: "Adam@adalogics.com"
auto_ccs :
  - "adam@adalogics.com"
  - "fjl@ethereum.org"
  - "martin.swende@ethereum.org"
  - "peter@ethereum.org"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
