homepage: "https://github.com/google/jsonnet"
primary_contact: "dcunnin@google.com"
auto_ccs:
  - "wwweiwang@google.com"
experimental: True

sanitizers:
  - address
  
labels:
  data_context_fuzzer:
    - sundew
