homepage: "https://github.com/awslabs/s2n"
language: c
primary_contact: "aweibel@amazon.com"
auto_ccs:
  - "soco@amazon.com"
  - "colm@apache.org"
  - "aws-security@amazon.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
architectures:
  - x86_64
