homepage: "https://github.com/libarchive/libarchive"
language: c++
primary_contact: "joerg.sonnenberger@googlemail.com"
auto_ccs:
  - "kientzle@gmail.com"
  - "martin@matuska.org"
  - "adam@adalogics.com"
sanitizers:
  - address
  - memory:
     experimental: True
  - undefined
