homepage: "https://xiph.org/flac/"
language: c++
primary_contact: "mvanb1@gmail.com"
auto_ccs:
 - "erik.de.castro.lopo@gmail.com"
vendor_ccs:
 - "twsmith@mozilla.com"
sanitizers:
 - address
 - undefined
 - memory
 - nalloc
architectures:
 - x86_64
 - i386
fuzzing_engines:
 - afl
 - honggfuzz
 - libfuzzer
coverage_extra_args: -ignore-filename-regex=/usr/lib/jvm/.*
main_repo: 'https://github.com/xiph/flac.git'
