homepage: "https://github.com/syoyo/tinyexr"
language: c++  # Example values: c, c++, go, rust.
primary_contact: "<primary_contact_email>"
fuzzing_engines:
    - libfuzzer
sanitizers:
    - address
    - undefined
