homepage: "https://github.com/videolan/vlc"
language: c
primary_contact: "security@videolan.org"
sanitizers:
  - address
  - undefined
main_repo: 'https://github.com/videolan/vlc'
fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer
