fuzzing_engines:
- libfuzzer
homepage: https://www.keycloak.org/
language: jvm
main_repo: https://github.com/keycloak/keycloak
sanitizers:
- address
vendor_ccs:
- adam@adalogics.com
- david@adalogics.com
- arthur.chan@adalogics.com
