homepage: "https://github.com/guidovranken/cryptofuzz"
primary_contact: "guidovranken@gmail.com"
auto_ccs:
    - "openssl-security@openssl.org"
    - "kurt@roeckx.be"
    - "caswell.matt@googlemail.com"
