homepage: "https://github.com/pest-parser/pest"
language: rust
primary_contact: "sebastien.boeuf@intel.com"
auto_ccs:
  - "michael2012zhao@hotmail.com"
  - "Henry.Wang@arm.com"
  - "robert.bradford@intel.com"
  - "samuel.e.ortiz@protonmail.com"

sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
main_repo: 'https://github.com/pest-parser/pest'