auto_ccs:
- evverx@gmail.com
- nicolas.iooss.ossfuzz@gmail.com
- omosnacek@gmail.com
- jwcart2@gmail.com
- cgzones@googlemail.com
- for.the.dawn.chorus@gmail.com
builds_per_day: 4
homepage: https://github.com/SELinuxProject/selinux
language: c
main_repo: https://github.com/SELinuxProject/selinux
primary_contact: nicolas.iooss_ossfuzzselinux@m4x.org
sanitizers:
- address
- undefined
- memory
