homepage: "https://pdfium.googlesource.com/pdfium"
primary_contact: "david@adalogics.com"
language: c++
fuzzing_engines:
- libfuzzer
- honggfuzz
sanitizers:
- address
main_repo: 'https://pdfium.googlesource.com/pdfium'
