homepage: "https://github.com/google/OpenSK"
main_repo: "https://github.com/google/OpenSK"
primary_contact: "david@adalogics.com"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
language: rust
auto_ccs:
  - "david@adalogics.com"
