homepage: "https://github.com/hyperium/"
main_repo: "https://github.com/hyperium/"
primary_contact: "david@adalogics.com"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
language: rust
auto_ccs:
  - "seanmonstar@gmail.com"
