homepage: "https://github.com/hyperium/http"
main_repo: "https://github.com/hyperium/http"
primary_contact: "david@adalogics.com"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
language: rust
auto_ccs:
  - "david@adalogics.com"
