homepage: "https://github.com/tpm2-software/tpm2-tss"
language: c++
primary_contact: "tadeusz.struk@intel.com"
auto_ccs:
  - "andreas.fuchs@sit.fraunhofer.de"
  - "john.s.andersen@intel.com"
  - "william.c.roberts@intel.com"
  - "tstruk@gmail.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://github.com/tpm2-software/tpm2-tss.git'
