homepage: "https://github.com/tbeu/matio"
language: c++
primary_contact: "t-beu@users.sourceforge.net"
auto_ccs:
  - "derobins@hdfgroup.org"
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
main_repo: "https://github.com/tbeu/matio"
fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer
