auto_ccs:
- miconda@gmail.com
- david@adalogics.com
- mail@gilawa.com
- qxork.droid@gmail.com
- for.the.dawn.chorus@gmail.com
homepage: www.kamailio.org
language: c
main_repo: https://github.com/kamailio/kamailio
primary_contact: ossfuzz@kamailio.org
