homepage: "http://unicode-rs.github.io/"
main_repo: "https://github.com/unicode-rs"
primary_contact: "david@adalogics.com"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
language: rust
auto_ccs:
  - "david@adalogics.com"
