name: Infra tests
on:
  pull_request:
    paths:
      - 'infra/cifuzz/**'
      - '.github/workflows/cifuzz_e2e_tests.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, coverage]

    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Build Fuzzers
        id: build
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@${{ github.head_ref }}
        with:
          build-integration-path: 'projects/cifuzz-example'
          oss-fuzz-project-name: ''
          sanitizer: ${{ matrix.sanitizer }}
      - name: Run Fuzzers
        id: run
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@${{ github.head_ref }}
        with:
          build-integration-path: 'projects/cifuzz-example'
          sanitizer: ${{ matrix.sanitizer }}
          oss-fuzz-project-name: ''
          fuzz-seconds: 600
          github-token: ${{ secrets.GITHUB_TOKEN }}
