name: Infra tests
on:
  pull_request:
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |  # Needed for git diff to work.
          git fetch origin master --depth 1
          git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/master

      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          which python
          sudo python -m pip install --upgrade pip
          sudo pip install -r infra/ci/requirements.txt
          sudo pip install -r infra/build/functions/requirements.txt

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '298.0.0'
      - run: |
          sudo gcloud components install beta cloud-datastore-emulator
          sudo gcloud info

      - name: Run infra tests
        run: sudo python infra/presubmit.py infra-tests


