homepage: "https://hyper.rs"
primary_contact: "sean@seanmonstar.com"
auto_ccs:
- "p.antoine@catenacyber.fr"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
language: rust
main_repo: 'https://github.com/hyperium/hyper'
